version: '2'
services:
#About node_modules.
#By default I override local node_modules directory.
#This is intended for working without installing dependencies by using development images.
  
#Bitcore Full Node
  bitcore-fullnode:
    image: quay.io/interactar/bitcorefullnode:master
    container_name: bitcore-fullnode
    networks:
      - bitcore   
    ports:
      - "3000:3001"
    volumes:
      - ./bitcoreroot:/root
      - ./nodecfg/public_bitcore-node.json:/root/mynode/bitcore-node.json
      - ./runBitcored.sh:/runBitcored.sh
    logging:
        driver: json-file
        options:
           max-size: "50m"
                        
    restart: always
    #for prod network > command: bitcore create mynode
    command: "/runBitcored.sh"


networks:
 bitcore:
     driver: bridge
