version: '2'
services:

#Bitcore Full Node
  bitcore-fullnode:
    image: quay.io/interactar/bitcorefullnode:master
    container_name: bitcore-fullnode
    links:
      - bitcore-db
    networks:
      - bitcore   
    #restart: always
    volumes:
      - ./bitcoreroot:/root
      - ./runBitcored.sh:/runBitcored.sh
                        
    #for prod network > command: bitcore create mynode
    command: "/runBitcored.sh testnet wallet" 
 
  #Bitcore Wallet Service
  wallet-service:
    image: quay.io/interactar/bitcorewalletservice:master
    container_name: wallet-service
    ports:
      - "3232:3232"
    volumes:
      - ./walletcfg/config.js:/bws/config.js
      - ./walletLogs:/bws/logs
      - ./runWalletService.sh:/runWalletService.sh
        #  volumes_from:
        #    - db
    networks:
      - bitcore   
    links:
      - bitcore-db
    command: '/runWalletService.sh'

  bitcore-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /srv/docker/mongodb:/data/db
    networks:
      - bitcore   
    #restart: always
    #
  #Bitcore Copay and BWS CLI
  copayAndBWSClient:
    image: quay.io/interactar/copayandbwsclient
    container_name: copay-bwscli
    ports:
      - "8100:8100"
#   volumes:
#     - ./copaycfg/externalServices.json:/copay/externalServices.json
    networks:
      - bitcore   

networks:
 bitcore:
     driver: bridge
